const projectUpdates = [
  // Project 1 updates
  {
    updateId: 1,
    projectId: 1,
    leaderId: 101,
    textContent: "Project kickoff meeting held successfully.",
    location: "New York, USA",
    mediaFiles: [{ type: "image", url: "https://example.com/kickoff.jpg" }],
    createdAt: "2024-03-01T09:00:00Z",
    createdBy: 201,
  },
  {
    updateId: 2,
    projectId: 1,
    leaderId: 101,
    textContent: "Requirement gathering completed.",
    location: "New York, USA",
    mediaFiles: [{ type: "document", url: "https://example.com/requirements.docx" }],
    createdAt: "2024-03-05T14:15:00Z",
    createdBy: 202,
  },
  {
    updateId: 3,
    projectId: 1,
    leaderId: 101,
    textContent: "Initial wireframes and designs are ready.",
    location: "New York, USA",
    mediaFiles: [{ type: "image", url: "https://example.com/wireframe.png" }],
    createdAt: "2024-03-10T11:45:00Z",
    createdBy: 203,
  },

  // Project 2 updates
  {
    updateId: 4,
    projectId: 2,
    leaderId: 102,
    textContent: "Database schema finalized.",
    location: "Los Angeles, USA",
    mediaFiles: [{ type: "pdf", url: "https://example.com/schema.pdf" }],
    createdAt: "2024-03-12T16:30:00Z",
    createdBy: 204,
  },
  {
    updateId: 5,
    projectId: 2,
    leaderId: 102,
    textContent: "Backend API development started.",
    location: "Los Angeles, USA",
    mediaFiles: [{ type: "video", url: "https://example.com/backend-demo.mp4" }],
    createdAt: "2024-03-15T10:00:00Z",
    createdBy: 205,
  },
  {
    updateId: 6,
    projectId: 2,
    leaderId: 102,
    textContent: "Testing environment set up successfully.",
    location: "Los Angeles, USA",
    mediaFiles: [{ type: "image", url: "https://example.com/testing.png" }],
    createdAt: "2024-03-18T09:30:00Z",
    createdBy: 206,
  },

  // Project 3 updates
  {
    updateId: 7,
    projectId: 3,
    leaderId: 103,
    textContent: "Front-end UI development has begun.",
    location: "Toronto, Canada",
    mediaFiles: [{ type: "image", url: "https://example.com/ui-design.png" }],
    createdAt: "2024-03-20T14:00:00Z",
    createdBy: 207,
  },
  {
    updateId: 8,
    projectId: 3,
    leaderId: 103,
    textContent: "Login and authentication module completed.",
    location: "Toronto, Canada",
    mediaFiles: [{ type: "document", url: "https://example.com/authentication.pdf" }],
    createdAt: "2024-03-22T17:45:00Z",
    createdBy: 208,
  },
  {
    updateId: 9,
    projectId: 3,
    leaderId: 103,
    textContent: "First round of QA testing completed.",
    location: "Toronto, Canada",
    mediaFiles: [{ type: "image", url: "https://example.com/qa-report.jpg" }],
    createdAt: "2024-03-25T11:15:00Z",
    createdBy: 209,
  },

  // Project 4 updates
  {
    updateId: 10,
    projectId: 4,
    leaderId: 104,
    textContent: "Deployment server configured successfully.",
    location: "London, UK",
    mediaFiles: [{ type: "video", url: "https://example.com/deployment.mp4" }],
    createdAt: "2024-03-28T13:30:00Z",
    createdBy: 210,
  },
  {
    updateId: 11,
    projectId: 4,
    leaderId: 104,
    textContent: "Security audit conducted and passed.",
    location: "London, UK",
    mediaFiles: [{ type: "document", url: "https://example.com/security-report.pdf" }],
    createdAt: "2024-03-30T15:20:00Z",
    createdBy: 211,
  },
  {
    updateId: 12,
    projectId: 4,
    leaderId: 104,
    textContent: "Final documentation completed.",
    location: "London, UK",
    mediaFiles: [{ type: "image", url: "https://example.com/doc-screenshot.png" }],
    createdAt: "2024-04-02T08:10:00Z",
    createdBy: 212,
  },

  // Project 5 updates
  {
    updateId: 13,
    projectId: 5,
    leaderId: 105,
    textContent: "Beta version released for testing.",
    location: "Berlin, Germany",
    mediaFiles: [{ type: "video", url: "https://example.com/beta-demo.mp4" }],
    createdAt: "2024-04-05T10:45:00Z",
    createdBy: 213,
  },
  {
    updateId: 14,
    projectId: 5,
    leaderId: 105,
    textContent: "User feedback collected and analyzed.",
    location: "Berlin, Germany",
    mediaFiles: [{ type: "document", url: "https://example.com/feedback-analysis.docx" }],
    createdAt: "2024-04-07T12:30:00Z",
    createdBy: 214,
  },
  {
    updateId: 15,
    projectId: 5,
    leaderId: 105,
    textContent: "Final release prepared for production.",
    location: "Berlin, Germany",
    mediaFiles: [{ type: "image", url: "https://example.com/release.png" }],
    createdAt: "2024-04-10T09:00:00Z",
    createdBy: 215,
  },
];

export default projectUpdates;
